project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Excercise"
      menu: 
        - text: "Hands-on Ex 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Ex 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Ex 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Handsonex03.html"
        - text: "Hands-on Ex 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Handsonex03b.html"
        - text: "Hands-on Ex 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Ex 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Ex 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Ex 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Ex 9a"
          href: "Hands-on_Ex/Hands-on_Ex09a/Hands-on_Ex08a.html"
        - text: "Hands-on Ex 9b"
          href: "Hands-on_Ex/Hands-on_Ex09b/Hands-on_Ex08b.html"
          
      
    - text: "Take Home Excercise"
      menu: 
        - text: "Take Home Ex 1"
          href: "Takehome_Ex/TakeHome Ex01/Takehomeex01.html"
        - text: "Take Home Ex 2"
          href: "Takehome_Ex/TakeHome Ex02/takehomeex02.html"
        - text: "Take Home Ex 3"
          href: "Takehome_Ex/TakeHome Ex03/Takehomeex03.html"
    
    - text: "In class Excercise"
      menu: 
        - text: "In Class Ex 1"
          href: "InClass_Ex/In class2/In-class_Ex02.html"
          
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    fontsize: 1.0em
    css: bootstrap.css
    toc: true
    toc-title: Table of Contents
    toc-depth: 4
    grid: 
      sidebar-width: 200px
      body-width: 850px
      margin-width: 300px

editor: visual
