project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Excercise"
      menu: 
        - text: "Hands-on Ex 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Ex 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Ex 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Handsonex03.html"
        - text: "Hands-on Ex 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Handsonex03b.html"
        - text: "Hands-on Ex 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Ex 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

